export const tickets = (state) => state.tickets.tickets
export const searchId = (state) => state.tickets.searchId
export const visibleTickets = (state) => state.tickets.visibleTickets
export const transplants = (state) => state.transplants
export const filters = (state) => state.filters
export const stop = (state) => state.tickets.stop
export const fetchSearchIDStatus = (state) => state.tickets.fetchSearchIDStatus
export const fetchGetTicketsStatus = (state) => state.tickets.fetchGetTicketsStatus
export const error = (state) => state.tickets.error
